Repository PhDN/NoCheat, pull requests merged in 2023-03, with the labels that each got.

#10 Update default port from port 80 to 8080
  devdocs.md
  src/back/main.py
Labels: bug, documentation

#6 Remove `python-magic` dependency
  environment.yml
  src/back/Controller.py
  src/test/test_controller.py
Labels: enhancement

#18 Backend CI Fix
  .github/workflows/actions.yml
  src/back/Controller.py
  src/test/data/test.txt
  src/test/test_controller.py
  src/test/test_model.py
Labels: testing

#12 test-model-cli
  src/back/model.py
  src/test/test_model.py
Labels: testing

#19 Frontend Documentation
  src/front/src/App.js
  src/front/src/DocumentItem.js
  src/front/src/DocumentPreview.js
  src/front/src/DocumentStore.js
  src/front/src/DocumentsForm.js
  src/front/src/EditModal.js
  src/front/src/IconButton.js
  src/front/src/JobItem.js
  src/front/src/JobStore.js
  src/front/src/JobsList.js
  src/front/src/Modal.js
  src/front/src/utils/documentStore.js
  src/front/src/utils/jobsStore.js
Labels: documentation

#22 Output detailed analysis to front-end
  src/back/Controller.py
  src/back/main.py
  src/back/model.py
  src/front/src/JobItem.js
  src/front/src/JobsList.css
  src/test/test_model.py
Labels: documentation, enhancement

#23 Created more backend tests
  src/test/data/chat-gpt_generated_text.doc
  src/test/data/chat-gpt_generated_text.docx
  src/test/data/chat-gpt_generated_text.pdf
  src/test/data/human_generated_text.doc
  src/test/data/human_generated_text.docx
  src/test/data/human_generated_text.pdf
  src/test/test_controller.py
Labels: testing
